### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by caveman7** [Pamblam/mysql-import#1]
Hello,

There will be "Unhandled promise rejection error" if there is an error during import function (in my case because the database does not exist). A more elegant error handling is required

`UnhandledPromiseRejectionWarning: Error: ER_BAD_DB_ERROR: Unknown database 'localkvs_local_org1'`

This is the code
```
const mysqlImporter = require('mysql-import');
const DUMP_DIR = `dumps/`;
const path = require('path');

mysqlImporter.config({
    host: 'localhost',
    port: 3306,
    user: 'root',
    password: 'root',
    database: 'localkvs_local_org1' //non-existent database
});

mysqlImporter.import(path.resolve(__dirname, DUMP_DIR, `localkvs_local_org1.sql`))
.then(() => {

})
.catch((err) => {
console.log(err);
});
```

**Comment by Pamblam** [comment]
ok.. i'll get that done as soon as i have a few minutes.. thanks for letting me know.

**Comment by Pamblam** [comment]
or if you wanna submit a pr that would be cool too

**Comment by Pamblam** [comment]
So, the config method doesn't return a Promise, and that's where your error is being thrown, so I've added an `onerror` property that you can use which will catch all errors. 

Otherwise, had there been an error thrown in the import process itself you catch would have worked exactly the way you had it.
