### ISSUE TITLE
Multiple import error

### ISSUE THREAD

**Issue by Arwantys** [Pamblam/mysql-import#2]
Sorry for my english, I'm French.

Hello, I am currently on a project and I need to be able to send several .sql import to a few seconds of interval, once socket.io receives an event its must execute and since it is about rather heavy file his plant, a solution? Thank's

Bonjour, je suis actuellement sur un projet et j'ai besoin de pouvoir envoyer plusieurs importation .sql à quelques secondes d'interval, une fois que socket.io reçoit un événement sa doit s'executer et vu qu'il s'agit de fichier assez lourd sa plante, une solution ? Merci.

**Comment by Pamblam** [comment]
Your Google translate didn't help. I'm not sure exactly what you need. Do you want to import multiple files simultaneously?

Votre traduction Google n'a pas aidé. Je ne suis pas sûr exactement de ce dont vous avez besoin. Voulez-vous importer plusieurs fichiers simultanément?

**Comment by Arwantys** [comment]
Here is the error with the code used
https://youtu.be/y6j3f5JAs-4

**Comment by Pamblam** [comment]
I am unable to re-produce this error.. can you share the code you used in the video with me? If you could put it on Github and share the link I can download it and test with your code. Here is what I tried:

Je suis incapable de reproduire cette erreur .. pouvez-vous partager le code que vous avez utilisé dans la vidéo avec moi? Si vous pouviez le mettre sur Github et partager le lien, je peux le télécharger et le tester avec votre code. Voici ce que j'ai essayé:

```
require('../mysql-import.js').config({
	host: 'localhost',
	user: 'root',
	password: 'password',
	database: 'testdb',
	onerror: err=>console.log(err.message)
}).import(__dirname+'/test.sql').then(()=> {
	console.log('all statements have been executed');
	require('../mysql-import.js').config({
		host: 'localhost',
		user: 'root',
		password: 'password',
		database: 'testdb2',
		onerror: err=>console.log(err.message)
	}).import(__dirname+'/test.sql').then(()=> {
		console.log('all statements have been executed');
	});
});
```

**Comment by Arwantys** [comment]
https://github.com/Arwantys/MySQL-Import

The input allows to choose a database, during an import in progress, to send the sql in another database.

Thanks

**Comment by Pamblam** [comment]
Thanks @Arwantys, 

The problem was that you were not waiting for the first import to finish before running the next import. I've fixed it so the `config` method creates a new instance every time it's called, so it will import to two databases simultaneously. Please update to version 1.0.7 and it will work with your existing code.

Also, you've left your MySQL login and password in the repo you shared.

+++++++++

Merci @Arwantys,

Le problème était que vous n'attendiez pas la première importation pour terminer l'importation suivante. Je l'ai corrigé pour que la méthode `config` crée une nouvelle instance à chaque fois qu'elle est appelée, elle importera donc simultanément vers deux bases de données. Veuillez mettre à jour à la version 1.0.7 et cela fonctionnera avec votre code existant.

De plus, vous avez laissé votre identifiant et votre mot de passe MySQL dans le dépôt que vous avez partagé.

**Comment by Arwantys** [comment]
Thank you very much !

For the identifiers it's local, it's nothing :)
